### ISSUE TITLE
Uploading an Object

### ISSUE THREAD

**Issue by PushAndRun** [opentelekomcloud-docs/object-storage-service#60]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/api-ref/source/getting_started/uploading_an_object.rst

Executing the code from the example with updated SK/AK and URL returns a 403 error. The error message states that the calculated and submitted signatures are different. I experienced the same issue when trying to build a request manually in JS.

**Comment by PushAndRun** [comment]
No sorry, I did not keep the project. But I pasted literally only the sample code from the linked page and updated the AK/SK as well as the OBS path.

**Comment by dsabelni** [comment]
No problem, I´ll try to replicate the issue.

**Comment by dsabelni** [comment]
I was able to replicate the problem, internal ticket was created.
Some points that may help to solve the problem while the documentation page is not yet updated:

- add the "Host" header to the request, which has a "bucket_name.obs_endpoint" structure, for example "somebucket.obs.eu-de.otc.t-systems.com". Java code: _httpPut.addHeader("Host", bucketName + '.' + endpointOBS); //bucketName and endpointOBS are moved to the class fields_
- if you are still getting an error, please check the Error/StringToSign value in the response body. This value is formed by the next rule: _HTTP-Verb + "\n" + Content-MD5 + "\n" + Content-Type + "\n" + Date + "\n" + CanonicalizedHeaders + CanonicalizedResource_, so if there is a Content-Type present in that value (for example, "text/plain; charset=ISO-8859-1"), try adding it to the contentType variable: _String contentType = "text/plain; charset=ISO-8859-1";_

**Comment by dsabelni** [comment]
Hello @PushAndRun ! After some discussions with colleagues we've came to the conclusion that the original code presented in the documentation works. My mistake when trying to get this code to work was that I've used OBS endpoint instead of the bucket endpoint (which consists of bucketName + OBSendpoint):
I were using
`HttpPut httpPut = new HttpPut("http://obs-endpoint/objecttest1");`
instead of
`HttpPut httpPut = new HttpPut("http://bucketname.obs-endpoint/objecttest1");`
when using the second option everything works for me. Can you please check if you were using the correct endpoint?

**Comment by PushAndRun** [comment]
Hi Dimitrii, Thanks for having another look into it! I included the bucket name but forgot the object name in the end... You are right, the code here is correct and the problem is between chair and screen. Sorry! However, I would propose to improve the error message. A 403 error message without additional information seems in this case misleading to me, even if it makes sense from a technical perspective.
