### ISSUE TITLE
Creating a Bucket

### ISSUE THREAD

**Issue by gekimmel** [opentelekomcloud-docs/object-storage-service#81]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/api-ref/source/apis/operations_on_buckets/creating_a_bucket.rst

We received customer feedback that x-obs-bucket-object-lock-enabled is not working. Instead x-amz-bucket-object-lock-enabled has to be used. Can you please check and either correct the API or the documentation. However, I hope this is the right context here. The full feedback was: 

_About the WORM feature, I was able to create the buckets with WORM feature using the OBS API.
Postman has a feature to calculate AWS S3 signature, which is the same method used by OTC, Huawei Cloud and other S3 similar services.
The biggest problem was that OTC documentation has wrong information. The header "x-obs-bucket-object-lock-enabled" should be 
"x-amz-bucket-object-lock-enabled". Took a while to find that, but now it is working_

**Comment by dsabelni** [comment]
Hello @gekimmel ! The WORM feature is available in both Native and S3 API, but right now there is no documentation for the S3 part (we expect to receive it closer to the end of January). So in the case of S3 API - it is correct, instead of _x-obs-_ headers the _x-amz-_ headers should be used. However there is no mistake in the documentation (as far as I can tell) - the link to the page you provided is for the Native API, and it works with _x-obs-_ headers.

**Comment by dsabelni** [comment]
FYI: information on the WORM feature is now available also for S3 documentation.
https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/doc/s3api/source/operations_on_buckets/put_bucket.rst : 

- Note on enabling WORM
- x-amz-bucket-object-lock-enabled in the Optional request headers table
- Sample Request and Response for Creating a Bucket with WORM Enabled
